---
server:
  port: 8080
  servlet:
    context-path: /

spring:
  thread-executor: virtual
  application:
    name: digital-lommebok-issuer-ui-demo
    environment: default


# Spring Boot Actuator
management:
  server:
    port: 8090
  endpoints:
    web:
      exposure:
        include: info,version,prometheus,health
      base-path: /
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
      environment: ${spring.application.environment}

issuer-ui-demo:
  issuer-server:
    issuance-endpoint: /api/v1/credential/issuance-transaction
    credential-configurations:
      - credential-configuration-id: no.skatteetaten.nnid_mso_mdoc
        description: Norsk identitetsnummer
        scope: eudiw:no:skatteetaten:nnid
        person-identifier: 50917500484
        json-request: |
          {
            "credential_configuration_id": "no.skatteetaten.nnid_mso_mdoc",
            "subject": {
              "identifier": "50917500484"
            },
            "claims": [
              {
                "name": "norwegian_national_id_number",
                "value": "50917500484"
              },
              {
                "name": "norwegian_national_id_number_type",
                "value": "D-nummer"
              }
            ]
          }
      - credential-configuration-id: no.minid.mpid_mso_mdoc
        description: MinID PID
        scope: eudiw:no:minid:mpid
        person-identifier: 24838674964
        json-request: |
          {
            "credential_configuration_id": "no.minid.mpid_mso_mdoc",
            "subject": {
              "identifier": "24838674964"
            },
            "claims": [
              {
                "name": "personal_administrative_number",
                "value": "24838674964"
              },
              {
                "name": "family_name",
                "value": "KJENDIS"
              },
              {
                "name": "given_name",
                "value": "UTØRST"
              },
              {
                "name": "birth_date",
                "value": "1886-03-24"
              },
              {
                "name": "expiry_date",
                "value": "2025-11-01"
              },
              {
                "name": "issuance_date",
                "value": "2025-09-17"
              }
            ]
          }
      - credential-configuration-id: no.advokattilsynet.advokatregisteret_mso_mdoc
        description: Advokatbevilling
        scope: eudiw:no:advokattilsynet:advokatregisteret
        person-identifier: 16903349844
        json-request: |
          {
            "credential_configuration_id": "no.advokattilsynet.advokatregisteret_mso_mdoc",
            "subject": {
              "identifier": "16903349844"
            }
          }
      - credential-configuration-id: no.kontaktregisteret.kontaktinformasjon_sd_jwt_vc
        description: Digital kontaktinformasjon
        scope: eudiw:no:kontaktregisteret:kontaktinformasjon
        person-identifier: 16903349844
        json-request: |
          {
            "credential_configuration_id": "no.kontaktregisteret.kontaktinformasjon_sd_jwt_vc",
            "subject": {
              "identifier": "16903349844"
            }
          }
# Maskinporten
maskinporten:
  lib:
    enabled: true
    issuer: dummy
    clients:
      default:
        client-id: ${MASKINPORTEN_CLIENT_ID}
        kid: ${MASKINPORTEN_CLIENT_KID}
        issuer: ${maskinporten.lib.issuer}
        audience:
          - ${maskinporten.lib.issuer}
        token-endpoint: ${maskinporten.lib.issuer}token
        scope: eudiw:no:skatteetaten:nnid eudiw:no:minid:mpid eudiw:no:advokattilsynet:advokatregisteret eudiw:no:kontaktregisteret:kontaktinformasjon
        resource: ${issuer-ui-demo.issuer-server.base-url}
        connect-timeout-ms: 5000
        read-timeout-ms: 2000
        key-store-name: default
idporten-key-manager:
  default-keystore: default
  keystores:
    default:
      key-store-type: JKS
      key-store-location: base64:${MASKINPORTEN_BASE64_KEYSTORE}
      key-store-password: ${MASKINPORTEN_KEYSTORE_PASSWORD}
      key-alias: ${MASKINPORTEN_KEYSTORE_ALIAS}
      key-password: ${MASKINPORTEN_KEY_PASSWORD}

# Digdir standard logging
digdir:
  access:
    logging:
      filtering:
        static-resources: true
