---
spring:
  application:
    environment: test

bevisgenerator:
  features:
    allow-bevistyper-v2: false
  byob-service:
    base-url: https://byob-service.test.eidas2sandkasse.net
  issuer-server:
    credential-issuer: https://utsteder.test.eidas2sandkasse.net
    demo-pid-credential-issuer: https://utsteder.test.eidas2sandkasse.net/demo-pid-issuer

maskinporten:
  lib:
    issuer: https://test.maskinporten.no/
