---
spring:
  application:
    environment: test
  data:
    redis:
      password: ${REDIS_PASSWORD}
      sentinel:
        master: mymaster
        password: ${REDIS_PASSWORD}
        nodes:
          - digital-lommebok-redis-ha-server-0.digital-lommebok-redis-ha:26379
          - digital-lommebok-redis-ha-server-1.digital-lommebok-redis-ha:26379
          - digital-lommebok-redis-ha-server-2.digital-lommebok-redis-ha:26379

bevisgenerator:
  features:
    allow-bevistyper-v2: false
  byob-service:
    base-url: https://byob-service.test.eidas2sandkasse.net
  issuer-server:
    credential-issuer: https://utsteder.test.eidas2sandkasse.net/bevisgenerator
    credential-issuer-pid: https://utsteder.test.eidas2sandkasse.net/pid
    credential-issuer-minid: https://utsteder.test.eidas2sandkasse.net/minid
    well-known-urls:
      - https://utsteder.test.eidas2sandkasse.net/.well-known/openid-credential-issuer/pid
      - https://utsteder.test.eidas2sandkasse.net/.well-known/openid-credential-issuer/minid
      - https://utsteder.test.eidas2sandkasse.net/.well-known/openid-credential-issuer/bevisgenerator
  verifier-service:
    base-url: https://verifier-service.test.eidas2sandkasse.net

maskinporten:
  lib:
    issuer: https://test.maskinporten.no/
